import { Geist, Geist_Mono, Londrina_Solid, Archivo_Narrow } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const LondrinaSolid = Londrina_Solid({
  variable: "--font-londrina",
  subsets: ["latin"],
  weight: ["100", "300", "400", "900"],
});

const ArchivoNarrow = Archivo_Narrow({
  variable: "--font-archivo",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${LondrinaSolid.variable} ${ArchivoNarrow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
